#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_acceil:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'main\index.html.twig'

app_delete:
  path: /delete/{nPrevensiss}
  controller: App\Controller\ListAccidentsController::delete


app_chartdate:
  path: /charts/{dateAccident}
  controller: App\Controller\ChartsController::accident

#app_edit:
#  path: /edit/{nPrevensiss}
#  controller: App\Controller\AjouteAccController::edit()

